version: "3"
services:
    web:
        image: node:12.16.3   #node镜像名称
        working_dir: /client      #工作目录
        volumes:                #挂载点
            - ..:/client       #把本地当前目录挂载到容器的/client目录
        ports:                  #端口映射
            - "3000:3000"   #本地端口：容器端口
        command: npm run dev      #这条命令会在工作目录下执行
    mysql:
        image: mysql:5.6
        volumes:
            - ./data:/var/lib/mysql     #挂载当前的data目录到容器默认mysql存储目录
            - ./mysql:/docker-entrypoint-initdb.d
        environment:                        #环境变量
            - MYSQL_ROOT_PASSWORD=sa123456    #mysql的root密码
            - MYSQL_DATABASE=pokemon     #mysql的初始化数据库
        ports:
            - "3306:3306"
    nginx:
        image: nginx:1.17
        volumes:
            - ./static:/client/static
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf    #挂在nginx服务的配置文件到容器里
        ports:
            - "80:80"